In [9]:
import pandas as p
import numpy as n
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB

In [10]:
df = p.read_csv("ecommerce_product_dataset_650.csv")
df.head()

                                 product_description        category
0  Comfortable women's high waisted denim jeans w...        Clothing
1  Biography of an influential tech leader and co...           Books
2  Curved gaming monitor 144Hz refresh rate with ...     Electronics
3  Interactive children's picture book with color...           Books
4                                                NaN  Home & Kitchen

In [11]:
df.isnull().sum()

product_description    38
category               24
dtype: int64

In [12]:
df = df.dropna().reset_index(drop=True)

In [13]:
df.head()

                                 product_description        category
0  Comfortable women's high waisted denim jeans w...        Clothing
1  Biography of an influential tech leader and co...           Books
2  Curved gaming monitor 144Hz refresh rate with ...     Electronics
3  Interactive children's picture book with color...           Books
4  Non-stick cookware set including frying pans a...  Home & Kitchen

In [14]:
from sklearn.tree import DecisionTreeClassifier

train_x = df["product_description"]
train_y = df["category"]

x_train, x_test, y_train, y_test = train_test_split(
    train_x, train_y, test_size=0.2, random_state=42, stratify=train_y
)

vectorizer = CountVectorizer()
x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

model = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced"
)
model.fit(x_train_vec, y_train)

predictions = model.predict(x_test_vec)

print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions))

nb_model = MultinomialNB()
nb_model.fit(x_train_vec, y_train)

nb_predictions = nb_model.predict(x_test_vec)

print("Naive Bayes Classification Report:")
print(classification_report(y_test, nb_predictions))

Decision Tree Classification Report:
                precision    recall  f1-score   support

         Books       1.00      1.00      1.00        26
      Clothing       1.00      1.00      1.00        29
   Electronics       1.00      1.00      1.00        35
Home & Kitchen       1.00      1.00      1.00        29

      accuracy                           1.00       119
     macro avg       1.00      1.00      1.00       119
  weighted avg       1.00      1.00      1.00       119

Naive Bayes Classification Report:
                precision    recall  f1-score   support

         Books       1.00      1.00      1.00        26
      Clothing       1.00      1.00      1.00        29
   Electronics       1.00      1.00      1.00        35
Home & Kitchen       1.00      1.00      1.00        29

      accuracy                           1.00       119
     macro avg       1.00      1.00      1.00       119
  weighted avg       1.00      1.00      1.00       119

In [15]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(x_train_vec, y_train)
rf_predictions = rf_model.predict(x_test_vec)

print("Random Forest Classification Report:")
print(classification_report(y_test, rf_predictions))

Random Forest Classification Report:
                precision    recall  f1-score   support

         Books       1.00      1.00      1.00        26
      Clothing       1.00      1.00      1.00        29
   Electronics       1.00      1.00      1.00        35
Home & Kitchen       1.00      1.00      1.00        29

      accuracy                           1.00       119
     macro avg       1.00      1.00      1.00       119
  weighted avg       1.00      1.00      1.00       119

In [16]:
new_description = [
    "Stainless steel chef knife set with ergonomic handle and wooden block."
]
new_description_vec = vectorizer.transform(new_description)

decision_tree_predictions = model.predict(new_description_vec)
naive_bayes_predictions = nb_model.predict(new_description_vec)
rf_predictions = rf_model.predict(new_description_vec)

new_data = p.DataFrame({
    "description": new_description,
    "decision_tree_prediction": decision_tree_predictions,
    "naive_bayes_prediction": naive_bayes_predictions,
    "randomforest_prediction": rf_predictions
})

new_data

,description,decision_tree_prediction,naive_bayes_prediction,randomforest_prediction
0,Stainless steel chef knife set with ergonomic ...,Home & Kitchen,Home & Kitchen,Home & Kitchen