In [20]:
import pandas as p
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [21]:
df = p.read_csv("student_course_reviews_500.csv")

In [22]:
df

                                           review_text sentiment
0    Loved how the professor connected theoretical ...  Positive
1    Lectures often went off-topic and missed core ...  Negative
2    Syllabus was updated with latest tools and ind...  Positive
3    Great peer learning environment and active stu...  Positive
4    Neutral opinion overall, it meets basic course...   Neutral
..                                                 ...       ...
495  The course load was overwhelming given the cre...  Negative
496  The instructor was often late and unorganized ...  Negative
497  Disorganized schedule with constant rescheduli...  Negative
498  Fairly standard course with expected workload ...   Neutral
499  Lectures are standard, nothing exceptional but...   Neutral

[500 rows x 2 columns]

In [23]:
df.isnull()

     review_text  sentiment
0          False      False
1          False      False
2          False      False
3          False      False
4          False      False
..           ...        ...
495        False      False
496        False      False
497        False      False
498        False      False
499        False      False

[500 rows x 2 columns]

In [24]:
df.isnull().sum()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_text  475 non-null    str
 1   sentiment    485 non-null    str
dtypes: str(2)
memory usage: 44.4 KB

In [25]:
df = df.dropna().reset_index(drop=True)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_text  460 non-null    str
 1   sentiment    460 non-null    str
dtypes: str(2)
memory usage: 42.5 KB

In [27]:
df.loc[1:40, ['review_text', 'sentiment']]

                                          review_text sentiment
1   Lectures often went off-topic and missed core ...  Negative
2   Syllabus was updated with latest tools and ind...  Positive
3   Great peer learning environment and active stu...  Positive
4   Neutral opinion overall, it meets basic course...   Neutral
5   Note: Excellent support during office hours fr...  Positive
6   I loved the practical hands-on projects; they ...  Positive
7   Felt like a complete waste of time and tuition...  Negative
8   Very good learning experience overall, worth t...  Positive
9   Terrible communication from the professor rega...  Negative
10  Note: The lecture slides were very detailed an...  Positive
11  Inspiring domain expert taught the class, thor...  Positive
12  Class schedule was well planned and followed t...  Positive
13  Loved how the professor connected theoretical ...  Positive
14  Assignment instructions were vague and constan...  Negative
15  Felt like the instructor was reading directly ...  Negative
16  Syllabus was updated with latest tools and ind...  Positive
17  The instructor was often late and unorganized ...  Negative
18  Fantastic experience! The real-world case stud...  Positive
19  The workload is manageable, neither too heavy ...   Neutral
20  Assignment instructions were vague and constan...  Negative
21  Harsh grading without constructive feedback pr...  Negative
22  Note: Super helpful TA who conducted optional ...  Positive
23  Highly recommended for anyone looking to build...  Positive
24  Felt like a complete waste of time and tuition...  Negative
25  Fantastic experience! The real-world case stud...  Positive
26  The grading criteria are completely unfair and...  Negative
27  Fantastic experience! The real-world case stud...  Positive
28  Outdated slides with broken code examples that...  Negative
29  Comprehensive syllabus that prepares you well ...  Positive
30  The lecture slides were very detailed and easy...  Positive
31  Note: Teaching style is a bit dry, but slides ...   Neutral
32  Great balance of group work and individual ass...  Positive
33  Assignments were graded way too late in the se...  Negative
34  The interactive quizzes after each module real...  Positive
35  Loved how the professor connected theoretical ...  Positive
36  Note: The lecture slides were very detailed an...  Positive
37  Neither good nor bad, just a typical universit...   Neutral
38  Highly recommended for anyone looking to build...  Positive
39  Great peer learning environment and active stu...  Positive
40  Highly recommended for anyone looking to build...  Positive

In [28]:
df.loc[0:8, 'sentiment']

0    Positive
1    Negative
2    Positive
3    Positive
4     Neutral
5    Positive
6    Positive
7    Negative
8    Positive
Name: sentiment, dtype: str

In [29]:
from sklearn.tree import DecisionTreeClassifier

train_x = df["review_text"]
train_y = df["sentiment"]

x_train, x_test, y_train, y_test = train_test_split(
    train_x, train_y, test_size=0.2, random_state=42, stratify=train_y
)

vectorizer = CountVectorizer()
x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

model = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced"
)
model.fit(x_train_vec, y_train)

predictions = model.predict(x_test_vec)

print("Decision Tree Classification Report:")
print(classification_report(y_test, predictions))

nb_model = MultinomialNB()
nb_model.fit(x_train_vec, y_train)

nb_predictions = nb_model.predict(x_test_vec)

print("Naive Bayes Classification Report:")
print(classification_report(y_test, nb_predictions))

Decision Tree Classification Report:
              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00        35
     Neutral       1.00      1.00      1.00        20
    Positive       1.00      1.00      1.00        37

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92

Naive Bayes Classification Report:
              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00        35
     Neutral       1.00      1.00      1.00        20
    Positive       1.00      1.00      1.00        37

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92

In [30]:
new_reviews = [
    "The instructor was knowledgeable, and the lessons were clear and engaging.",
    "The course was poorly organized, and the assignments were confusing.",
    "The workload was reasonable, and the course content was satisfactory.",
    "Excellent practical activities and helpful feedback from the instructor."
]

new_reviews_vec = vectorizer.transform(new_reviews)

decision_tree_predictions = model.predict(new_reviews_vec)
naive_bayes_predictions = nb_model.predict(new_reviews_vec)

new_data = p.DataFrame({
    "review_text": new_reviews,
    "decision_tree_prediction": decision_tree_predictions,
    "naive_bayes_prediction": naive_bayes_predictions
})

new_data

,review_text,decision_tree_prediction,naive_bayes_prediction
0,"The instructor was knowledgeable, and the less...",Negative,Positive
1,"The course was poorly organized, and the assig...",Negative,Negative
2,"The workload was reasonable, and the course co...",Negative,Neutral
3,Excellent practical activities and helpful fee...,Negative,Positive

In [31]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(x_train_vec, y_train)
rf_predictions = rf_model.predict(x_test_vec)

print("Random Forest Classification Report:")
print(classification_report(y_test, rf_predictions))

Random Forest Classification Report:
              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00        35
     Neutral       1.00      1.00      1.00        20
    Positive       1.00      1.00      1.00        37

    accuracy                           1.00        92
   macro avg       1.00      1.00      1.00        92
weighted avg       1.00      1.00      1.00        92

In [32]:
new_reviews = [
    "The instructor was knowledgeable, and the lessons were clear and engaging.",
    "The course was poorly organized, and the assignments were confusing.",
    "The workload was reasonable, and the course content was satisfactory.",
    "Excellent practical activities and helpful feedback from the instructor."
]

new_reviews_vec = vectorizer.transform(new_reviews)

decision_tree_predictions = model.predict(new_reviews_vec)
naive_bayes_predictions = nb_model.predict(new_reviews_vec)
rf_predictions = rf_model.predict(new_reviews_vec)


new_data = p.DataFrame({
    "review_text": new_reviews,
    "decision_tree_prediction": decision_tree_predictions,
    "naive_bayes_prediction": naive_bayes_predictions,
    "randomforest_prediction": rf_predictions
})

new_data

,review_text,decision_tree_prediction,naive_bayes_prediction,randomforest_prediction
0,"The instructor was knowledgeable, and the less...",Negative,Positive,Positive
1,"The course was poorly organized, and the assig...",Negative,Negative,Negative
2,"The workload was reasonable, and the course co...",Negative,Neutral,Neutral
3,Excellent practical activities and helpful fee...,Negative,Positive,Positive